services:
  - type: web
    name: norheimsposten-server
    runtime: node
    buildCommand: pnpm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://norheimspostenv2.onrender.com

  - type: static
    name: norheimsposten-client
    buildCommand: pnpm install && pnpm --filter client build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://norheimspostenwebservice.onrender.com
