name = "norheimsposten-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "norheimsposten-db"
database_id = "bf177eb8-b175-4607-9245-9f55c81ab40b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "norheimsposten-uploads"

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,https://norheimsposten-client.pages.dev,https://norheimsposten.no"
